default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: starmetal_development
  username: postgres
  password: iam3489495

test:
  <<: *default
  database: starmetal_test
  username: postgres
  password: iam3489495

production:
  <<: *default
  database: starmetal_production
  username: starmetal
  password: <%= ENV["METAL_DATABASE_PASSWORD"] %>
